### ISSUE TITLE
CM flow: Reconfigure Current CM dashboard: Students page. [ENG]

### ISSUE THREAD

**Issue by tessathornberry** [sfbrigade/compass#107]
## Behaviors of the updated Students page:

- [x] Contains an Add Students component prompting requirements for their first name, last name, and e-mail address, with an "Add Student" button
- [x] Once any students have been added, their first and last names (and possibly e-mail addresses) render below the "add student" component, sorted by order entered or perhaps by last name, if you wish.
- [x] clicking on a student's name links to that student's page in pages/student/student_id

- [x] Optionally render the total number of students, as in the example, default 0.

### This issue will likely require restructuring between the pages and components files.
Most of the functions and mapping have been figured out, and are available for copying and/or review from components/case_manager/AllStudents
#### Rather than renaming, moving, or deleting files, please make new files. You can always comment out the original files after copying usable code. 
You want to be sure your branch works before any deletion or alteration of the original files.
Once your branch works, you can delete the original file (e.g. in src/components if you are instead using a file in src/pages) if you are ready to push your PR.

States:

![Image](https://github.com/sfbrigade/compass/assets/105292208/90096509-95e4-4de8-90c8-9414e67baacc)

(imagine the students and e-mails are unique!)
![Image](https://github.com/sfbrigade/compass/assets/105292208/4075e471-983c-4476-b144-ccca6148af62)

(please ignore table contents and focus on button placement when the "Add Students" component is not visible:
![Image](https://github.com/sfbrigade/compass/assets/105292208/5c2674f2-04b5-4daa-8547-9ae9ca8f6e88)

**Comment by codetheweb** [comment]
Blocked by #106.

**Comment by tessathornberry** [comment]
This is no longer blocked - it has been revised to be open to assignment.
