### ISSUE TITLE
CM flow: Reconfigure CM Dashboard: Staff page. [ENG]

### ISSUE THREAD

**Issue by tessathornberry** [sfbrigade/compass#108]
## Behaviors of the updated Staff page:

- [ ] Contains an Add Staff component prompting requirements for their first name, last name, e-mail address, and (optional)phone number, with an "Add Staff" button
- [ ] Once any staff have been added, their first and last names, email addresses and phone numbers(if inputted) render below the "add staff" component, sorted by order entered or perhaps by last name, if you wish.
- [ ] clicking on a staff member's name links to that staff member's page in pages/paras/user_id

- [ ] Optionally render the total number of staff, as in the example, default 1.

### This issue will likely require restructuring between the pages and components files.
Most of the functions and mapping have been figured out, and are available for copying and/or review from components/case_manager/AllParas
#### Rather than renaming, moving, or deleting files, make new files. You can always comment out the original files after copying usable code. 
You want to be sure your branch works before any deletion or alteration of the original files.
Once your branch works, you can delete the original file (e.g. in src/components if you are instead using a file in src/pages) if you are ready to push your PR.

States:

![Image](https://user-images.githubusercontent.com/105292208/244580813-cd644feb-6aba-4f73-97bc-9506d401ada3.png)

![Image](https://user-images.githubusercontent.com/105292208/244580946-ff0ac068-d12f-4998-8780-e841fdca7528.png)

![Image](https://user-images.githubusercontent.com/105292208/244581053-54a79ff4-566e-4bf7-96a7-d3f7d622ba75.png)

**Comment by codetheweb** [comment]
Blocked by #106.

**Comment by tessathornberry** [comment]
This is no longer blocked - it has been revised to be open to assignment.
