### ISSUE TITLE
CM flow: Make reusable search component for searching both students and staff. [ENG]

### ISSUE THREAD

**Issue by tessathornberry** [sfbrigade/compass#109]
It would be ideal if issues #106, #107, and #108 were completed and merged before this one is started.

Feel free to look at src/components/case_manager/PersonCreationForm.tsx for an example of a reusable form.

- [ ] Make a form that takes in the first names, last names, and email of a list of people, and filters by a user-inputted string. Make the results clickable to that person's page in pages.
- [ ] Insert into Staff page and Student page

**Comment by codetheweb** [comment]
Blocked by https://github.com/sfbrigade/compass/issues/106, https://github.com/sfbrigade/compass/issues/107, and https://github.com/sfbrigade/compass/issues/108

**Comment by tessathornberry** [comment]
Unblocked and ready for development.
