### ISSUE TITLE
CM flow: Create student's individual pages [Eng]

### ISSUE THREAD

**Issue by jonahchoi** [sfbrigade/compass#152]
- [ ] Create tabs for each category (goals, staff, etc.)
- [ ] Render goals in goals tab
- [ ] On click, dropdown should show benchmarks(subgoals) relating to goal
- [ ] Each benchmark should show basic info, star/favorite button, and view more button
- [ ] Button to add new goals (probably a modal, tbd)

![Image](https://github.com/sfbrigade/compass/assets/104597125/e6881634-e237-4a56-a442-cebd707d8f77)

![Image](https://github.com/sfbrigade/compass/assets/104597125/69a34f31-fe04-420d-aa90-0eac561cf761)

**Comment by jonahchoi** [comment]
Blocked by goals/subgoals/tasks backend

**Comment by jonahchoi** [comment]
Unblocked now that backend is merged

**Comment by KCCPMG** [comment]
Most recent draft of student page (still pending):



![Image](https://github.com/sfbrigade/compass/assets/39074889/04eebb4d-99b2-423a-80c8-0e0d3c2c9a5f)
