### ISSUE TITLE
Convert all functional components to not use React.FC and Capitalize first letter

### ISSUE THREAD

**Issue by jonahchoi** [sfbrigade/compass#154]
Rewrite all functional components to use the pattern 
`Component = ({ destructuredProps }: Props) => {}`  
Although Nextjs pages seem to work with lowercase components, we should stick to React conventions with a capital first letter for all components.
Refer to https://github.com/facebook/create-react-app/pull/8177 for more info on FC.

**Comment by AmreetKumarkhuntia** [comment]
Hello I can help out with this one
