### ISSUE TITLE
Fix 401 error when not logged in. [Eng]

### ISSUE THREAD

**Issue by jonahchoi** [sfbrigade/compass#161]
The navbar is currently using the `getMe` query to determine what to render, but as its an authenticated procedure, a 401 error pops up when not logged in. It might be helpful to talk to @codetheweb about creating a new procedure that doesn't require auth, or find another way to determine if a user is logged in.

**Comment by codetheweb** [comment]
`import { useSession } from "next-auth/react"` can be used to determine if a user is logged in
