### ISSUE TITLE
Use Light Compass icon on sidebar so that it appears more visible on dark sidebar background [ENG]

### ISSUE THREAD

**Issue by tessathornberry** [sfbrigade/compass#166]
Check with Design Team to get white version of Compass SVG file for addition to our image files. (We might still need the black version in the repo, btw.)
Contacts would be Tyler Matsunami and/or Miguel Hugo

![Image](https://user-images.githubusercontent.com/105292208/257390176-d03b361f-1200-4ae2-b2bb-c73879a15d57.png)

![Image](https://github.com/sfbrigade/compass/assets/105292208/37cb836f-7f16-480a-8230-d44b86969d95)

**Comment by miguel-hugo** [comment]
![Image](https://github.com/sfbrigade/compass/assets/66722820/ebf6e312-40c4-404e-b21f-d3096e5874cf)
