### ISSUE TITLE
Allow choosing a file in the UploadImage component with a single click [ENG]

### ISSUE THREAD

**Issue by codetheweb** [sfbrigade/compass#189]
See thread here: https://github.com/sfbrigade/compass/pull/139/files#r1267508331

**Comment by shin101** [comment]
Quick question before I potentially assign myself to this issue -

1) It seems like UploadImageComponent from [#139](https://github.com/sfbrigade/compass/pull/139) is not rendered anywhere. Are we still using this? 
2) We already have http://localhost:3000/files that allows us to choose a file with a single click, we could potentially use this?

**Comment by codetheweb** [comment]
> It seems like UploadImageComponent from https://github.com/sfbrigade/compass/pull/139 is not rendered anywhere. Are we still using this?

Not using it yet, but it will eventually be part of the para flow.

> We already have http://localhost:3000/files that allows us to choose a file with a single click, we could potentially use this?

Yes, but the `<UploadImageComponent/>` is the styled variant. It also should have more functionality (see https://github.com/sfbrigade/compass/issues/190).

**Comment by shin101** [comment]
> > It seems like UploadImageComponent from #139 is not rendered anywhere. Are we still using this?
> 
> Not using it yet, but it will eventually be part of the para flow.
> 
> > We already have http://localhost:3000/files that allows us to choose a file with a single click, we could potentially use this?
> 
> Yes, but the `<UploadImageComponent/>` is the styled variant. It also should have more functionality (see #190).
