### ISSUE TITLE
UploadImage component should accept an optional existing `fileId` [ENG]

### ISSUE THREAD

**Issue by codetheweb** [sfbrigade/compass#190]
If an existing `fileId` is provided, the component will fetch the file details and display them (probably just the file name for now?).

**Comment by shin101** [comment]
I'd be happy to work on this but I'm a bit confused on what I'll be working on and why  - how can one provide fileId (by passing as a props?), if so why would one do that and why would this feature be needed?
Any context would be appreciated 🙏

**Comment by codetheweb** [comment]
If a user starts filling out a form and uploads a file then navigates away and comes back to finish it later, the input shouldn't appear empty. And yes, I was thinking it would be provided via a prop. 👍

**Comment by shin101** [comment]
Update - During our meeting today it was discussed that this feature is no longer a part of MVP so I will be prioritizing higher priority issues
