### ISSUE TITLE
Make "Edit" button/edit choices on Individual Student's Page [ENG]

### ISSUE THREAD

**Issue by tessathornberry** [sfbrigade/compass#199]
Take "Archive Student" Button and put it in this Edit Student menu/page instead of the Individual student's main page, and allow the CM ONLY to edit the student's name, grade, IEP date, and e-mail address. Correctly changed data updates the student entry and/or IEP date for THIS CM/Student combo in the database. (See how the data is stored and retrieved)

**Comment by tessathornberry** [comment]
Take out IEP date - unnecessary for the Student page

**Comment by BrettEastman** [comment]
Here is a more accurate breakdown of what we are doing with this ticket:

- Create view states for individual student page, one called MAIN with current student information (grade, IEP, goals, subgoals, etc.), and on called EDIT which presents the Edit view where the CM can edit individual student info
- Create EditStudentTable for EDIT view
- Take "Archive Student" Button and put it in this EDIT view
- Remove Return to Students button
- Add Cancel button
- Create authenticated procedure called editStudent for the CM ONLY (in src/backend/routers/case_manager.ts) to edit the student's name, grade, IEP date, and e-mail address
