### ISSUE TITLE
Fix or delete broken links [ENG]

### ISSUE THREAD

**Issue by tessathornberry** [sfbrigade/compass#202]
Initial versions of Compass before the Navbar had links in the individual student page and the individual staff page for the CM dashboard and MyStudents page. Many of these links are not needed and are also sometimes broken. Delete or fix links back to the student list and CM dashboard SPECIFICALLY ON:
1) The individual student page
2) The individual staff member page

**Comment by hieungo89** [comment]
This is the same issue as #184. It should be resolved soon so I will be closing this issue.
