### ISSUE TITLE
Add empty state for students, staff, etc. [ENG]

### ISSUE THREAD

**Issue by jonahchoi** [sfbrigade/compass#207]
Some new art was added to fill in the empty state for benchmarks, staff, etc. Please go through the skeletal designs to find all the new empty states, and implement them.

Ex:
https://www.figma.com/file/m09znscRXNqSziAiEbNLTf/Compass-Designs?type=design&node-id=7558-3671&mode=design&t=v7GSqATwtKoIFs2x-4

https://www.figma.com/file/m09znscRXNqSziAiEbNLTf/Compass-Designs?type=design&node-id=7497-12744&mode=design&t=v7GSqATwtKoIFs2x-4

**Comment by hieungo89** [comment]
This was brought up during the main group meeting. An empty state for staff is not needed because the staff page will always have 1 person in there.
