### ISSUE TITLE
Make Editing Goals possible [ENG]

### ISSUE THREAD

**Issue by tessathornberry** [sfbrigade/compass#216]
Currently once a user submits a goal, it is in the IEP's Goal list and cannot be edited.

We need users to be able to edit Goals in case of typos or adding them to the wrong student.
- [ ] Make goal text editable (see design link below)
- [ ] Make build match design CSS (see design link below)
Add more tickets for this issue if you need to split up the build and the CSS

**Comment by tessathornberry** [comment]
Figma: https://www.figma.com/file/m09znscRXNqSziAiEbNLTf/Compass-Designs?type=design&node-id=9340%3A22447&mode=design&t=cM4m4Vu4Zzq4iVFk-1

Designer: Vicky

**Comment by KCCPMG** [comment]
I just picked this up. Since this design is basically working from a prior design, I'm planning to update the [studentId] page to get to this design as well: [https://www.figma.com/file/m09znscRXNqSziAiEbNLTf/Compass-Designs?type=design&node-id=9340-22086&mode=design&t=Gr1qQK1vvGVhXkgp-0](url)

**Comment by KCCPMG** [comment]
> I just picked this up. Since this design is basically working from a prior design, I'm planning to update the [studentId] page to get to this design as well: [https://www.figma.com/file/m09znscRXNqSziAiEbNLTf/Compass-Designs?type=design&node-id=9340-22086&mode=design&t=Gr1qQK1vvGVhXkgp-0](url)

This aspect of the issue was broken off into issue #278 [#278](https://github.com/sfbrigade/compass/issues/278), which has since been closed.
