### ISSUE TITLE
CM flow: Para email invitation flow [Eng]

### ISSUE THREAD

**Issue by amantri** [sfbrigade/compass#29]
When a CM adds a new para, send an email invitation to the para's email. We will send an email invitation only if the para hasn't logged into Compass yet.

Things to figure out:
 - what happens if multiple CMs add the same para (before they have logged in). Should we send them multiple emails or just one?
 - Should we send reminder emails periodically if the para hasn't logged in?

**Comment by BrettEastman** [comment]
We have merged a PR which incorporates Nodemailer ability to automatically send an email when para is inputted by CM. We are still working on figuring out how to send reminder emails periodically.

**Comment by BrettEastman** [comment]
Great, thanks Francis! I am still learning, so both of these suggestions are super helpful. Anup also mentioned nodemailer-mock after yesterday's meeting.

**Comment by francisli** [comment]
Happy to help...! I'll also add that we're using this package:

https://www.npmjs.com/package/email-templates

So that we can create nice HTML + plaintext email templates...

**Comment by BrettEastman** [comment]
*Note: I have moved the email reminder to its own separate issue, Compass #123, to be looked at post-MVP.

**Comment by amantri** [comment]
Nice work on this Brett!
