### ISSUE TITLE
Update Edit Student to Modal to match Design Systems- styling [ENG]

### ISSUE THREAD

**Issue by tessathornberry** [sfbrigade/compass#302]
Note: Update Edit Student to Modal to match Design Systems divided into two separate tickets: modal and styling

UPDATE STUDENT AND STAFF Pages:

CURRENT VIEW:

![editiep](https://github.com/sfbrigade/compass/assets/105292208/f04fcbc5-d33d-4d56-b890-6283125a43ba)
Working out of pages/students/[student_id]

- [x] - Align CSS of Edit Student modal component  with Design Systems, though use your best judgment since the designs for this modal have not been worked on much

- [x]  - Please try to come up with an input type for date that looks clean - a calendar icon is OK, but the date input size, border, etc, should be the same as the text inputs if possible

![Edit student profile S2](https://github.com/sfbrigade/compass/assets/105292208/d1968b9d-85ce-48dc-847f-29dd536c8d01)

**Comment by katconnors** [comment]
Divided the ticket into two- the other ticket can be seen here: https://github.com/sfbrigade/compass/issues/314

**Comment by katconnors** [comment]
Updated to done, in response to Hannah's recent PR
