### ISSUE TITLE
Add authentication - Login with Google

### ISSUE THREAD

**Issue by amantri** [sfbrigade/compass#31]
#login

**Comment by amantri** [comment]
Justin added basic Google oauth support in this commit: https://github.com/sfbrigade/project-compass/commit/0d3734001a2dc85372325094605b9417225be655

**Comment by codetheweb** [comment]
Looks cool!

My main note is that I don't think we want to be using `next-auth` here since it requires a Next.js API route (in other words, it takes over the token exchange lifecycle--we should probably be doing that on the Express backend instead).

**Comment by amantri** [comment]
Ah ok. What are the benefits of managing the token exchange lifecycle ourselves?

**Comment by codetheweb** [comment]
I think I might have misremembered how next-auth works, functionally it seems good for our use case but I don't see a way to use it directly in Express without a Next.js API route unfortunately.
