### ISSUE TITLE
Create Updated create benchmark flow [ENG]

### ISSUE THREAD

**Issue by nikobooth** [sfbrigade/compass#324]
Neha has updated the create benchmark flow to collect all the information needed for a staff member to understand the data collection task. We have a ticket in progress to deploy the previous design. Need to decide how to get from what's in progress to the new design.

Yun, Katrina, Connor to discuss.

New design [Figma](https://www.figma.com/file/m09znscRXNqSziAiEbNLTf/Compass-Designs?type=design&node-id=13077-24231&mode=design&t=ev6EhVxqxp2sQTjX-11)

Following checklist is not exhaustive:
- [ ] Breakdown Into separate tickets (Connor is in progress on this writeup, tbd discussion)
- [ ] https://github.com/sfbrigade/compass/issues/325

**Comment by nikobooth** [comment]
Main updates in new design:

- Tabs in goal view for `All` & `Completed` benchmaks
- New inputs: Attemps per trial & Number of trials
- Creation is now a two step flow with a new stepper component

**Comment by KCCPMG** [comment]
![Image](https://github.com/sfbrigade/compass/assets/39074889/255b1591-9571-4f21-a980-051b46c080b0)


![Image](https://github.com/sfbrigade/compass/assets/39074889/ef6e411f-d252-41d7-90b9-b5f1c8f4e514)


![Image](https://github.com/sfbrigade/compass/assets/39074889/95bbcc65-a90c-455b-9b67-0fbbf409e588)


![Image](https://github.com/sfbrigade/compass/assets/39074889/7db9b6f2-48a5-4f11-b827-5a6140bfbf4a)


![Image](https://github.com/sfbrigade/compass/assets/39074889/ec2c0c3e-f6a2-48d5-a8de-06ba62283a6d)

**Comment by chengtchris1** [comment]
Working on creating the Benchmark list tile. Here is the branch I created
https://github.com/sfbrigade/compass/tree/Created-benchmark-view-new-design

**Comment by KCCPMG** [comment]
Created issue #339 to handle the database update aspect. This needs to be handled before the styling can be done, as the data being passed to pages and components will be different from the current version.

**Comment by KCCPMG** [comment]
Issue #339 closed

**Comment by KCCPMG** [comment]
Issue [#341](https://github.com/sfbrigade/compass/issues/341) created to address `students/[student_id]/goals/[goal_id]` page, assigned to @chengtchris1 .

**Comment by KCCPMG** [comment]
Issue [#342](https://github.com/sfbrigade/compass/issues/342) created to address `students/[student_id]/goals/[goal_id]/create` page. This issue should now have all parts extracted into their own issues, marking as closed.
