### ISSUE TITLE
Create Updated Benchmark Flow: Update [goal_id]/create page for benchmark creation [ENG]

### ISSUE THREAD

**Issue by KCCPMG** [sfbrigade/compass#342]
Update `students/[student_id]/goals/[goal_id]/create` page to accommodate the two-step benchmark creation form as per the new designs. The Figma designs can be found [here](https://www.figma.com/file/m09znscRXNqSziAiEbNLTf/Compass-Designs?type=design&node-id=13077-24231&mode=design&t=ev6EhVxqxp2sQTjX-11), and the images can be seen below:

![Image](https://github.com/sfbrigade/compass/assets/39074889/ef6e411f-d252-41d7-90b9-b5f1c8f4e514)
![Image](https://github.com/sfbrigade/compass/assets/39074889/95bbcc65-a90c-455b-9b67-0fbbf409e588)

Summary of Potential Action Items

- [ ] Implement in the Design Systems a "Stepper" component. [MaterialUI provides this](https://mui.com/material-ui/react-stepper/#customized-horizontal-stepper), though I'm not sure if one of these formats will match the design. If necessary, this can be extracted to a separate issue and replaced here with a placeholder.
- [ ] Redo the submission form so that it matches the design, including that it appears across two "pages" within the page. This logic should likely be extracted to its own component, and all of this will probably be a large task.

**Comment by nickvisut** [comment]
Stepper component ticket here: https://github.com/sfbrigade/compass/issues/325
