### ISSUE TITLE
[Para] Assigned Page - Sort

### ISSUE THREAD

**Issue by tam-janice** [sfbrigade/compass#424]
As a para who has been assigned multiple benchmarks by the CM, I want to be able to sort my list of benchmarks so I can easily find the one I'm working on with a particular student

AC
Given a Para has logged in to their account
When they are on the 'assigned' page
They can sort using a dropdown

Given a Para has opened the dropdown
When they select 'Date assigned'
Then they can see the newest assigned benchmark at the top

Given a Para has opened the dropdown
When they select 'Student'
Then they can see the benchmarks alphabetical by student first name

Given a Para has logged in to their account
When they are on the 'assigned' page
The default sort is 'Student'

Link to design: https://www.figma.com/design/m09znscRXNqSziAiEbNLTf/Compass-Designs?node-id=14403-17081&t=NdiL4IQhZBJgYBKQ-1

Questions

Notes

- [ ] We do not yet store the date that we assign a benchmark to a para. We could by default use the created_at date on a task, but IMO the date should be stored explicitly, and be in a new PR.
- [ ] This will necessitate that we do not allow reassignment of a task by changing the assignee, only be creating a new task.
- [ ] Add tests

**Comment by tam-janice** [comment]
10/15/2024 Blocker
Couldn't figure out how to assign to a para and switch to a para as if we are logged in. This is related to issue #450 

Workaround currently is to assign to an accoutn that is already logged in and then change the role of that signed in account to Para

**Comment by nickvisut** [comment]
Additional workaround is to temporarily comment out this part of the
relevant "get tasks" query in `para.ts` :
//.where("task.assignee_id", "=", userId)

**Comment by canjalal** [comment]
Vince to add tests

**Comment by canjalal** [comment]
We do not yet store the date that we assign a benchmark to a para. We could by default use the created_at date on a task, but IMO the date should be stored explicitly, and be in a new PR.

**Comment by canjalal** [comment]
Adding seeds for tasks, but the tasks's assignee id should be changed to an actual para's user_id once we are able to log in  as an actual para and not just our first user.

**Comment by canjalal** [comment]
Add frontend testing framework to the initial PR
