### ISSUE TITLE
Duplicate tasks for same benchmark and para should not be creatable (backend)

### ISSUE THREAD

**Issue by nickvisut** [sfbrigade/compass#439]
# ACTUAL

If case manager attempts to assign a benchmark to Para "A", then tries to assign the benchmark to Para "A" once more, the database will create a second task with the same benchmark and para

---

# EXPECTED

If case manager attempts to assign a benchmark to Para "A", then tries to assign the benchmark to Para "A" once more, the app should not allow the case manager to actually create a duplicate task assigned to Para "A". Duplicate rows in the `tasks` table should not be created no matter what. There should be a uniqueness constraint with the scope of benchmark and para.

**Comment by nickvisut** [comment]
cc @canjalal

**Comment by tam-janice** [comment]
Case manager view

Backend Issue: We can create multiple task assigments though the API

UI issue: Separate task - have the UI properly reflect the assign list
