### ISSUE TITLE
Make relational tables/schema and archive flow for students and CMs [ENG]

### ISSUE THREAD

**Issue by tessathornberry** [sfbrigade/compass#62]
In order to make an archive property for students, we will need relational tables to describe CM's relation to students, using the UUID's for both parties:

This may change slightly based upon if/how we restructure the CM and Para to both be Users.
- [x] Backend Make schema/table for CMs-to-students
- [x] Backend: make a "create student" action in the front end flow through this sequence of queries in the back end(while carrying CM uuid as part of the req object or otherwise having access to it in the backend):
    - [x] Backend:  Query for the student (by email) in the Student table 
    - [x] Backend query: If they do not exist, add student from query body to their primary table
    - [x] Backend: Either way, retrieve uuid of student (while carrying CM uuid)
- [x] ~Backend: Put CM's uuid and student's uuid in CM-to-student relational table (Do we need student names here also?)~

- [x] Frontend: Render student lists as the response to queries of the CM-to-student table (CM's uuid in that specific relational table)
- [x] Front-end: Make button for archiving student

- [x] Back-end: have CM-adding-student flow in. routers/students.ts:
* Is student email already in student table?
    * If no, add student
    * If yes, is assigned_case_manager_id **null?**
        * if no, send error message ('there is already a CM assigned to this student')
        * if yes (it's null), add case current manager's id to assigned_case_manager_id property

![image](https://user-images.githubusercontent.com/105292208/234747397-89cc0887-e4c8-42a3-8366-b1ca6136f014.png)
![image](https://user-images.githubusercontent.com/105292208/234747451-ad224673-a07e-4c9d-a9a1-a357bd9de957.png)

**Comment by amantri** [comment]
For the student change, we need to update the student table, and for the paras, we need to introduce a new case_manager_para relation table. Since these two are different, it might be good to break this out into two separate issues.

**Comment by amantri** [comment]
Thanks Tessa!

**Comment by tessathornberry** [comment]
OK, I updated the comment per thte current work:

- [ ] Back-end: have CM-adding-student flow in. routers/students.ts:
* If email is already in student table
    * If no, add student
    * If yes, check if assigned_case_manager_id is null
        * if no, send error message ('there is already a CM assigned to this student')
        * if yes (it's null), add case manager's id to assigned_case_manager_id property

**Comment by hieungo89** [comment]
I made 5 case scenarios when adding students:
- Student not in database
- Student in database with no case manager
- Student in database with different case manager
- Student already added by same case manager
- any unknown error not associated with other scenarios

An alert message will appear for the last 3 scenarios.
