### ISSUE TITLE
Flesh out MVP data model for Compass [Eng]

### ISSUE THREAD

**Issue by amantri** [sfbrigade/compass#90]
Flesh out the data model parts that are needed for the MVP CM and para flows.

Parts to flesh out:
 - structure of IEP, goals and benchmarks
 - Data collection for a trial
 - data collection scheduling (which populates tasks on the para dashboard)

**Comment by Code4Dopamine** [comment]
Mermaid.js Code Test:
How to use:
- Use an Editor like [Online Mermaid (UML) Creator] (https://mermaid.live/) or install plugins for [VSCode](https://mermaid.js.org/ecosystem/integrations.html#editor-plugins), etc.
- Commit the mermaid.js file normally

> For more, visit [here](https://mermaid.js.org/) and [here(Github Blog)](https://github.blog/2022-02-14-include-diagrams-markdown-files-mermaid/)

Demo Below:
```mermaid
classDiagram
    Main <|-- CaseManager
    Main <|-- Para
    Main <|-- Student
    class CaseManager{
      +String uuid
      +Method1()
      +Method2()
    }
    class Para{
      +String uuid
      +Array[] Tasks
      +Method1()
    }
    class Student{
      +String uuid
      +Method1()
    }
```
