### ISSUE TITLE
Para flow: Create React component for student card for para dashboard [Eng]

### ISSUE THREAD

**Issue by amantri** [sfbrigade/compass#92]
Each card represents a data collection activity for the para. 

Flesh out the API - inputs needed to render the card, and create reusable components that follow the design system in collaboration with the UX team.

Figma: https://www.figma.com/file/m09znscRXNqSziAiEbNLTf/Compass-Wireframes?type=design&node-id=4197-70119&t=duBg5z5djAaQ44DF-4

Mocks:
<img src="https://user-images.githubusercontent.com/829820/242450000-d3fbf27a-b8dc-4113-a599-330f15600002.png" width=40%>

**Comment by codetheweb** [comment]
Blocked by missing backend procedures.

**Comment by jonahchoi** [comment]
Unblocked by backend
