### ISSUE TITLE
Para flow: Attach images to a trial data collection [Eng]

### ISSUE THREAD

**Issue by amantri** [sfbrigade/compass#95]
Upload the images to the cloud and associate it with the trial data collection.

Figma: https://www.figma.com/file/m09znscRXNqSziAiEbNLTf/Compass-Wireframes?type=design&node-id=4197-70166&t=duBg5z5djAaQ44DF-4

Mocks:

<img src="https://github.com/sfbrigade/compass/assets/829820/159304e0-65bc-41ec-aa0f-f251129f4f94" width=40%>

**Comment by MarkOfosu** [comment]
This looks interesting to me and so I am happy to start working on it. Hopefully, I can make my first pull request soon!!

**Comment by codetheweb** [comment]
The resulting React component should use the `.getPresignedUrlForFileUpload()` and `.finishfileUpload()` procedures to upload files to the backend (see `src/backend/routers/files.test.ts` for example usage). The component API should look something like:

```tsx
<FileUpload fileIds={[]} onChange={() => { ... }}/>
```

where

```ts
interface FileUploadOptions {
  fileIds: string[]
  onChange: (newFileIds: string[]) => void
}
```

**Comment by MarkOfosu** [comment]
is the take a picture of students' work button in the image that came with the ticket the same as the file upload component that is shown above?

**Comment by codetheweb** [comment]
Yep, you'll probably want to add another prop to the above example component to allow customizing the title.

**Comment by MarkOfosu** [comment]
Also, at what point are the images actually uploaded? Is it right after the user selects the image?

**Comment by codetheweb** [comment]
It's up to you. I would:

- open the file picker / camera after clicking the button
- when control is given back to our application and something has been selected, start the upload, disable the button, and add an activity indicator
- once the upload is finished change the state of the button to indicate that the file has been uploaded (maybe a checkmark and/or show the file name?)

**Comment by MarkOfosu** [comment]
Thanks Max!
