### ISSUE TITLE
CM flow: Add Link to go back to Home page when Compass icon is clicked [ENG]

### ISSUE THREAD

**Issue by hieungo89** [sfbrigade/compass#97]
- [ ] Add a link for every Compass Logo to take the user back to the home page. All the possible places that are needed are:
    - [ ] cmDashboard
    - [ ] individual student's page - add the logo and redirect to home page
    - [ ] individual para's page - add the logo and redirect to home page

**Comment by priya1011** [comment]
@hieungo89 I would like to take on this issue, I will create a pull request with the changes once I have completed the implementation. Looking forward to contributing to the project!

**Comment by codetheweb** [comment]
hey @priya1011, are you still planning on working on this? if so feel free to assign yourself to this issue :)

**Comment by amantri** [comment]
The navbar (#106) will have the link to the home page and it should be on every page. Can this issue be marked as a duplicate of that one?

**Comment by BeeSeeWhy** [comment]
The navbar will be including this.
